### ISSUE TITLE
Add MaterialBottomSheet control

### ISSUE THREAD

**Issue by AgustinBonilla** [HorusSoftwareUY/MaterialDesignControlsPlugin#111]
https://m3.material.io/components/bottom-sheets/overview

**Comment by SnowPowerCore** [comment]
Hi, would be really happy to see it also🔥

**Comment by AgustinBonilla** [comment]
Hi @SnowPowerCore , we're currently developing an initial, basic iteration of this control, set to be included in the forthcoming release of the NuGet package.

**Comment by SnowPowerCore** [comment]
That is amazing to hear!
