### ISSUE TITLE
Add support for FontImageSource

### ISSUE THREAD

**Issue by sammyas12** [HorusSoftwareUY/MaterialDesignControlsPlugin#13]
It does not allow you to assign icons from a font family.
`<FontImageSource 
                                FontFamily="materialdesignicons-webfont.ttf#Material Design Icons"
                                Glyph="&#xfb2f;" Size="24" Color="{DynamicResource AccentText}" />`

**Comment by AgustinBonilla** [comment]
Hi, sorry about the delay, in which control do you need support for that image source?

**Comment by AgustinBonilla** [comment]
Currently, we have support for any kind of Icon in our controls through the CustomLeadingIcon and CustomTrailingIcon. If you continue having problems using a Font icon let us know and feel free to open this issue again.
