### ISSUE TITLE
MaterialEntry IsRequired and RequiredMessage Properties disappeared

### ISSUE THREAD

**Issue by mytahir** [HorusSoftwareUY/MaterialDesignControlsPlugin#31]
I tried to use IsRequired and RequiredMessage Properties on MaterialEntry but they are gone, is there something on this Update?

**Comment by AgustinBonilla** [comment]
Hi Mustapha, we removed both properties a few versions ago in a breaking change version, now we decided to move this responsibility out of the package and allow the dev to handle it to their preferences. Currently, you can handle it on your side by doing your own IsRequired validation and showing RequiredMessage in the AssistiveText property.
