### ISSUE TITLE
'Default constructor not found for type Plugin.MaterialDesignControls.iOS.TouchAndPressEffect

### ISSUE THREAD

**Issue by isarzhan** [HorusSoftwareUY/MaterialDesignControlsPlugin#4]

**Comment by AgustinBonilla** [comment]
@isarzhan Can you share more information about this issue? I reviewed the TouchAndPressEffect and this not have constructors with parameters, it also inherits the default constructor form PlatformEffect.

**Comment by AgustinBonilla** [comment]
I couldn't reproduce the issue. If it continues to happen, feel free to reopen it.
