### ISSUE TITLE
Quick overview

### ISSUE THREAD

**Issue by Luisalvarenga** [HorusSoftwareUY/MaterialDesignControlsPlugin#40]
Hi, I really liked the way this package is build and there's something that I am still wondering, for example when debugging the example app and then I go to the Material Entry's page,fill an entry and then try to clear the text from the entry this doesn't seem to respond, there's also similar aspect with the password entry with the enable the view of it eventhough I have checked that the source code integrates this behavior by default, is there something I'm missing?

**Comment by AgustinBonilla** [comment]
Hi Luis, thanks for using this package and helping us to improve it, yes, we have an issue related to both things in our latest versions. We have a ticket in our backlog to fix it, I hope that we can fix it soon.

**Comment by AgustinBonilla** [comment]
We fixed this issue on the v1.11.2 release. Thank you for your feedback!
