### ISSUE TITLE
CustomPasswordIcon not working

### ISSUE THREAD

**Issue by dolapobabs** [HorusSoftwareUY/MaterialDesignControlsPlugin#41]
CustomShowPassword and CustomHidePass not working in debug and release mode in the current version, 1.11.1. Previous version works in debug not in release. Is this specific to my projects

**Comment by AgustinBonilla** [comment]
Hi, thanks for using this package and helping us to improve it, yes, we have an issue related to both things in our latest versions. We have a ticket in our backlog to fix it, I hope that we can fix it soon.

**Comment by AgustinBonilla** [comment]
We fixed this issue on the v1.11.2 release. Thank you for your feedback!
