### ISSUE TITLE
Focus on Button Click

### ISSUE THREAD

**Issue by salmank63** [HorusSoftwareUY/MaterialDesignControlsPlugin#5]
How to open double picker on button click event?

**Comment by AgustinBonilla** [comment]
Hi @salmank63, currently, controls haven't support to do focus programmatically. However, I'll try to add this feature today.

**Comment by salmank63** [comment]
Thank you @AgustinBonilla 😊. Really need this feature, hope you will add it soon👍

**Comment by AgustinBonilla** [comment]
We added focus support on the v1.6.1 release. Thank you @salmank63 for your feedback!

**Comment by salmank63** [comment]
Thank you @AgustinBonilla for quickly adding this valuable feature. Your plugin is really helpful.
