### ISSUE TITLE
[BUG] Material entry border has uncolored parts

### ISSUE THREAD

**Issue by LinMoskovitch** [HorusSoftwareUY/MaterialDesignControlsPlugin#67]
Hi all,
I am developing an Android app and using the MaterialDesignControlsPlugin Nuget package
I have a weird UI bug as shown in the image below that the entries have uncolored spaces on them.
It happens only on entries in all colors and even without colors.
I tried to run in debug mode as well, restarted my IDE, and even switched Android device and API and none of this worked.
Have you ever issued this before or know how to solve this?

![image](https://user-images.githubusercontent.com/82546057/232853593-baa426b4-b2db-48e4-b5ef-da392f91497b.png)

Here is the XAML for one of the entries as well ( all of the entries have similar attributes)

Thank you for your reference.

` 
                                <Frame
                                    BackgroundColor="Transparent"
                                    BorderColor="#EEEEEE"
                                    CornerRadius="30"
                                    HorizontalOptions="FillAndExpand"
                                    Padding="0">
                                    <StackLayout Orientation="Vertical">
                                        <StackLayout>
                                            <material:MaterialEntry
                                                AnimateError="True"
                                                BackgroundColor="Transparent"
                                                BorderColor="{Binding NameBorderColor}"
                                                FontSize="16"
                                                MaxLength="25"
                                                Opacity="0.5"
                                                Placeholder="Name"
                                                PlaceholderColor="#EEEEEE"
                                                ReturnType="Next"
                                                TabIndex="1"
                                                Text="{Binding Name}"
                                                TextColor="#EEEEEE"
                                                Type="Filled" />
                                        </StackLayout>
                                    </StackLayout>
                                </Frame>`

**Comment by AgustinBonilla** [comment]
Hi! We have never seen that kind of error on Android. As I can see you have the entry inside a Frame and two StackLayout, have you tried removing them?

**Comment by LinMoskovitch** [comment]
Thanks for the quick response!
I will try that now

**Comment by LinMoskovitch** [comment]
> Hi! We have never seen that kind of error on Android. As I can see you have the entry inside a Frame and two StackLayout, have you tried removing them?

Removed 1 of the stackLayout, it didn't help :(

**Comment by AgustinBonilla** [comment]
and removing the Frame?

**Comment by LinMoskovitch** [comment]
By removing the Frame I lost the BorderRadius and it returns to a rectangle shape.

**Comment by AgustinBonilla** [comment]
MaterialEntry has a CornerRadius property that allows you to handle the BorderRadius and you can remove that Frame to test it

**Comment by LinMoskovitch** [comment]
I switched to a rectangular shape instead. Thanks
