### ISSUE TITLE
Add support for emojis in MaterialEntry and MaterialEditor

### ISSUE THREAD

**Issue by AgustinBonilla** [HorusSoftwareUY/MaterialDesignControlsPlugin#86]

**Comment by agaldanaw2** [comment]
![image](https://github.com/HorusSoftwareUY/MaterialDesignControlsPlugin/assets/83594458/a8109b56-40b1-411d-bacc-41e77620ad8f)
It's supported now.

**Comment by AgustinBonilla** [comment]
We are excited to announce that we are working on a new generation of controls based on Material Design V3, which we will be releasing soon.
This ticket has been included/fixed in the upcoming version of this NuGet package, which will include both current and new generations of controls.
